In [ ]:
# This Code helps to Convert the User Data into Chunks

In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('Azure_Spark_E-com_project/6M-0K-99K.users.dataset.public.csv')

In [8]:
df.head()

,identifierHash,type,country,language,socialNbFollowers,socialNbFollows,socialProductsLiked,productsListed,productsSold,productsPassRate,...,civilityTitle,hasAnyApp,hasAndroidApp,hasIosApp,hasProfilePicture,daysSinceLastLogin,seniority,seniorityAsMonths,seniorityAsYears,countryCode
0,-7279641312655250028,user,Etats-Unis,en,3,8,0,0,0,0.0,...,mrs,False,False,False,True,709,3205,106.83,8.9,us
1,-1456013578740053406,user,Allemagne,de,3,8,0,0,0,0.0,...,mrs,False,False,False,True,709,3205,106.83,8.9,de
2,9006282053848196165,user,Suède,en,3,8,0,0,0,0.0,...,mr,True,False,True,True,689,3205,106.83,8.9,se
3,-7154634866120535654,user,Turquie,en,3,8,0,0,0,0.0,...,mrs,False,False,False,True,709,3205,106.83,8.9,tr
4,2858299215060733023,user,France,en,3,8,0,0,0,0.0,...,mr,True,False,True,True,709,3205,106.83,8.9,fr

In [10]:
# Calculate the size of each chunk
chunk_size = len(df) // 5 + (1 if len(df) % 5 else 0)

# Split the dataframe into chunks and save them
for i in range(5):
    start = i * chunk_size
    end = start + chunk_size
    chunk_df = df.iloc[start:end]
    chunk_df.to_csv(f'Azure_Spark_E-com_project/chunk-data/chunk{i+1}.csv', index=False)